#!/usr/bin/env node

import { userInfo } from 'node:os';
import { JsStore } from '@animalabs/chronicle';
import { createOfflineRecoveryBranch } from './offline-branch.js';
import {
  DiscordAwarenessOutbox,
  defaultDiscordAwarenessOutboxPath,
  type DiscordAwarenessMarks,
} from './discord-awareness-outbox.js';
import {
  OperatorLog,
  defaultOperatorLogPath,
  type OperatorLogInput,
  type OperatorRequester,
} from '../operator-log.js';
import { RecordJournal } from '../record-journal.js';
import {
  cutAttemptDisposition,
  OPERATOR_CHANGES_JOURNAL,
  readOperatorChanges,
  type OperatorChangeRecord,
  type OperatorChangeResolution,
  type OperatorChangeResolutionReceipt,
  type OperatorChangesEntry,
  type OperatorChangesSnapshot,
} from '../operator-change.js';

interface CliOptions {
  storePath?: string;
  agentName?: string;
  messageId?: string;
  contextId?: string;
  messages?: number;
  suppressMessageIds: string[];
  suppressRanges: Array<{ fromMessageId: string; toMessageId: string }>;
  branchName?: string;
  namespace?: string;
  discordServerId?: string;
  outboxPath?: string;
  emoji?: string;
  marks: 'none' | 'addressed' | 'all';
  awareness?: { verb: 'list' | 'cancel' | 'retract' | 'release'; target?: string };
  operatorChange?: { verb: 'list' } | { verb: 'resolve'; changeId: string };
  attempt?: number;
  verdict?: 'committed' | 'not-committed';
  reason?: string;
  requester?: string;
  dryRun: boolean;
}

function usage(): string {
  return `Usage:
  agent-framework-recover --store <path> --agent <name> <anchor> [options]
  agent-framework-recover --store <path> --awareness <list|cancel ID|retract ID|all|release ID>
                              (cancel takes a batch id or a retract request id)
  agent-framework-recover --store <path> --operator-change list
  agent-framework-recover --store <path> --operator-change resolve <changeId> --attempt <n>
                              --verdict <committed|not-committed> --reason <text> [--requester <name>]

Creates and activates a Chronicle recovery branch while the normal host is
down. The recovery is local to the resident: by default no Discord reaction is
placed. --marks chooses to mark removed Discord messages with an awareness
reaction (queued here, delivered when the host and its Discord MCPL server
next connect). Message content is never compiled or written to the journal.

Options:
  --message-id <id|link>      Last Discord message the agent should still see
  --context-id <internal-id>  Exact internal context message to retain as anchor
  --messages <count>          Legacy alternative: remove N context entries
  --suppress <id|link>        Suppress one Discord message; repeat or comma-separate
  --suppress-range <a>..<b>   Suppress an inclusive context range; repeatable
  --branch <name>             Recovery branch name (generated by default)
  --namespace <namespace>     Context namespace (default: agents/<agent>)
  --discord-server <id>       Override/inject the Discord MCPL server id
  --marks <none|addressed|all>
                              Awareness marks on removed Discord messages
                              (default none; addressed = mentions, replies to
                              the bot and DMs; all = every addressable message)
  --outbox <path>             A pre-journal awareness ledger to import
                              (default: <store>/recovery/discord-awareness-outbox.json)
  --emoji <emoji>             Marker reaction (default: 💤)
  --dry-run                   Inspect a recovery's counts/addresses without
                              writing (a recovery only; refused with --awareness)
  --help                      Show this help

Awareness journal (host stopped):
  --awareness list            Each batch: scope, counts by status, holds
  --awareness cancel <ID>     Stop further sends of a batch's marks, or of a
                              retract's removals (never undoes anything)
  --awareness retract <ID|all>
                              Queue removal of this bot's marks (through each
                              ref's configured MCPL route) on a batch's refs,
                              or on every ref an add was ever sent for
  --awareness release <ID>    Queue a held batch's recorded operations
  Each acts at once: inspect first with --awareness list.

Gated operator changes (host stopped):
  --operator-change list      Each held change: an attempt whose switch and
                              failure were never recorded, with its evidence
  --operator-change resolve <changeId>
                              Record your verdict on its unresolved attempt
                              (--attempt, --verdict, --reason required), as
                              your attestation, distinct from what the
                              framework observed. not-committed abandons the
                              attempt; if its destination is the active
                              branch, the next start restores the source
                              before any agent initializes. A fresh attempt
                              is the host's decision. committed attests that it applied:
                              the next start establishes its outcome and
                              activates its staged marks before any traffic.

Queued work is delivered when the host next connects to the Discord server.
Each recovery, and each cancel, retract or release, is recorded in
<store>/operator-actions.jsonl, the host's operator log, with the OS account
that ran it, whether it was carried out or refused. A dry run and a list
record nothing.
The agent host must be stopped before running this command.`;
}

function parseArgs(args: string[]): CliOptions {
  const options: CliOptions = { dryRun: false, suppressMessageIds: [], suppressRanges: [], marks: 'none' };
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    const value = () => {
      const next = args[++i];
      if (!next) throw new Error(`${arg} requires a value`);
      return next;
    };
    switch (arg) {
      case '--store': options.storePath = value(); break;
      case '--agent': options.agentName = value(); break;
      case '--message-id':
      case '--message': options.messageId = value(); break;
      case '--context-id': options.contextId = value(); break;
      case '--messages': options.messages = Number(value()); break;
      case '--suppress':
      case '--suppress-message':
        options.suppressMessageIds.push(...value().split(',').map((item) => item.trim()).filter(Boolean));
        break;
      case '--suppress-range': {
        const raw = value();
        const separator = raw.indexOf('..');
        if (separator <= 0 || separator >= raw.length - 2) {
          throw new Error('--suppress-range must be formatted as <first>..<last>');
        }
        options.suppressRanges.push({
          fromMessageId: raw.slice(0, separator),
          toMessageId: raw.slice(separator + 2),
        });
        break;
      }
      case '--branch': options.branchName = value(); break;
      case '--namespace': options.namespace = value(); break;
      case '--discord-server': options.discordServerId = value(); break;
      case '--outbox': options.outboxPath = value(); break;
      case '--emoji': options.emoji = value(); break;
      case '--marks': {
        const marks = value();
        if (marks !== 'none' && marks !== 'addressed' && marks !== 'all') {
          throw new Error('--marks must be none, addressed or all');
        }
        options.marks = marks;
        break;
      }
      case '--awareness': {
        const verb = value();
        if (verb === 'list') {
          options.awareness = { verb };
        } else if (verb === 'cancel' || verb === 'retract' || verb === 'release') {
          options.awareness = { verb, target: value() };
        } else {
          throw new Error('--awareness must be list, cancel <ID>, retract <ID|all> or release <ID>');
        }
        break;
      }
      case '--operator-change': {
        const verb = value();
        if (verb === 'list') options.operatorChange = { verb };
        else if (verb === 'resolve') options.operatorChange = { verb, changeId: value() };
        else throw new Error('--operator-change must be list or resolve <changeId>');
        break;
      }
      case '--attempt': options.attempt = Number(value()); break;
      case '--verdict': {
        const verdict = value();
        if (verdict !== 'committed' && verdict !== 'not-committed') throw new Error('--verdict must be committed or not-committed');
        options.verdict = verdict;
        break;
      }
      case '--reason': options.reason = value(); break;
      case '--requester': options.requester = value(); break;
      case '--dry-run': options.dryRun = true; break;
      case '--help':
      case '-h':
        console.log(usage());
        process.exit(0);
      default: throw new Error(`Unknown argument: ${arg}`);
    }
  }
  return options;
}

/** Who ran the command, as far as the CLI can say: the OS account. */
function cliRequester(): OperatorRequester {
  try {
    return { via: 'cli', name: userInfo().username };
  } catch {
    return { via: 'cli' };
  }
}

/**
 * Record an act in the store's operator log (`<store>/operator-actions.jsonl`,
 * where the host records its own), whether it was done or refused, like the
 * live surfaces' acts. Best-effort: a logging failure never fails the act.
 */
function recordOperatorAction(storePath: string, entry: OperatorLogInput): void {
  new OperatorLog(defaultOperatorLogPath(storePath)).append(entry);
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function awareness(options: CliOptions): void {
  // The journal lives in the store; with the host stopped, this process is
  // its only writer.
  const store = JsStore.openOrCreate({ path: options.storePath! });
  try {
    const outbox = new DiscordAwarenessOutbox(store, {
      legacyPath: options.outboxPath ?? defaultDiscordAwarenessOutboxPath(options.storePath!),
    });
    const { verb, target } = options.awareness!;
    if (verb === 'list') {
      console.log(JSON.stringify({ store: options.storePath, batches: outbox.view() }, null, 2));
      return;
    }
    const by = 'agent-framework-recover';
    // Logged as the live controls log theirs.
    const logBase: OperatorLogInput = {
      kind: `awareness-${verb}`,
      agent: '*',
      requester: cliRequester(),
      params: verb === 'release' ? { batchId: target } : { target },
    };
    let result: object;
    try {
      result = verb === 'cancel' ? outbox.cancel(target!, by)
        : verb === 'retract' ? outbox.retract(target!, by)
        : outbox.release(target!, by);
    } catch (error) {
      recordOperatorAction(options.storePath!, { ...logBase, error: errorMessage(error) });
      throw error;
    }
    recordOperatorAction(options.storePath!, { ...logBase, result: { ...result } });
    console.log(JSON.stringify(result, null, 2));
  } finally {
    store.close();
  }
}

/**
 * The operator/changes journal with the host stopped: list the held changes,
 * or record an operator's verdict on one. This process is the store's only
 * writer, which stands in for the running framework's lease.
 */
function operatorChange(options: CliOptions): void {
  const store = JsStore.openOrCreate({ path: options.storePath! });
  try {
    const journal = new RecordJournal<OperatorChangesEntry, OperatorChangesSnapshot>(store, { type: OPERATOR_CHANGES_JOURNAL });
    // A journal that can't be interpreted is refused, never read as empty.
    const records = readOperatorChanges(journal.load());
    const active = store.currentBranch().name;
    const held = (record: OperatorChangeRecord) => {
      if (record.outcome || record.dropped || (record.kind !== 'undo-turns' && record.kind !== 'undo-messages')) return null;
      const last = record.attempts[record.attempts.length - 1];
      return last && cutAttemptDisposition(record, last) === 'unresolved' ? last : null;
    };
    const command = options.operatorChange!;
    if (command.verb === 'list') {
      const unresolved = [...records.values()].flatMap((record) => {
        const attempt = held(record);
        if (!attempt) return [];
        const { target, source, removed, marks } = attempt.evidence;
        return [{
          changeId: record.changeId,
          kind: record.kind,
          agent: record.agent,
          attempt: attempt.n,
          source,
          target,
          targetIsActive: active === target,
          targetExists: store.listBranches().some((b) => b.name === target),
          removed,
          marks: { scope: marks.scope, refs: marks.refs.length, unmarked: marks.unmarked, notRemoved: marks.notRemoved },
        }];
      });
      console.log(JSON.stringify({ store: options.storePath, activeBranch: active, unresolved }, null, 2));
      return;
    }
    const record = records.get(command.changeId);
    const attempt = record ? held(record) : null;
    if (!record || !attempt) throw new Error(`Operator change ${command.changeId} has no unresolved attempt to settle`);
    if (options.attempt !== attempt.n) throw new Error(`--attempt ${options.attempt} is not its unresolved attempt (${attempt.n} is)`);
    if (!options.verdict) throw new Error('--verdict committed|not-committed is required');
    if (!options.reason?.trim()) throw new Error('--reason is required');
    const resolution: OperatorChangeResolution = {
      verdict: options.verdict,
      reason: options.reason,
      requester: { via: 'agent-framework-recover', ...(options.requester ? { name: options.requester } : {}) },
      at: Date.now(),
      via: 'offline',
    };
    journal.append({ kind: 'resolved', changeId: record.changeId, n: attempt.n, resolution }, { durable: true });
    // Nothing in the store's body is touched here: a not-committed attempt
    // whose destination is the active branch gets its source back at the
    // next start, before any agent initializes on it.
    const restoresAtStart = options.verdict === 'not-committed' && active === attempt.evidence.target;
    const remaining = options.verdict === 'not-committed' && !restoresAtStart && active !== attempt.evidence.source
      ? `the active branch is ${active}, neither the source ${attempt.evidence.source} nor the attempt's destination`
      : undefined;
    const receipt: OperatorChangeResolutionReceipt = {
      changeId: record.changeId,
      attempt: attempt.n,
      recorded: resolution,
      settlement: options.verdict === 'committed'
        ? 'at the next start: startup establishes its outcome and activates its staged marks before any traffic'
        : `abandoned${restoresAtStart ? `; the next start restores ${attempt.evidence.source} before any agent initializes` : ''}; a fresh attempt is the host's decision on its next retry`,
      ...(remaining ? { remaining } : {}),
    };
    console.log(JSON.stringify(receipt, null, 2));
  } finally {
    store.close();
  }
}

async function main(): Promise<void> {
  const options = parseArgs(process.argv.slice(2));
  if (options.operatorChange) {
    if (!options.storePath) throw new Error(`--operator-change needs --store\n\n${usage()}`);
    operatorChange(options);
    return;
  }
  if (options.awareness) {
    if (!options.storePath) {
      throw new Error(`--awareness needs --store\n\n${usage()}`);
    }
    // There is no preview of a control: refuse rather than act on a command
    // that asked not to change anything.
    if (options.dryRun) {
      throw new Error('--dry-run previews a recovery; it does not apply to --awareness (inspect with --awareness list)');
    }
    awareness(options);
    return;
  }
  if (
    !options.storePath
    || !options.agentName
    || (!options.messageId && !options.contextId && options.messages === undefined)
  ) {
    throw new Error(`--store, --agent, and one anchor (--message-id, --context-id, or --messages) are required\n\n${usage()}`);
  }

  // A CLI choice and its application are the same moment (the host is
  // stopped), so the scope is evaluated now rather than frozen to refs.
  const marks: DiscordAwarenessMarks = options.marks === 'none' ? 'none' : { scope: options.marks };
  // A real recovery is recorded in the operator log, done or failed, with
  // its marks choice and receipt, as a live rollback or suppression is. A
  // dry run changes nothing and records nothing.
  const logBase: OperatorLogInput = {
    kind: 'recovery',
    agent: options.agentName,
    requester: cliRequester(),
    params: {
      ...(options.messageId !== undefined ? { messageId: options.messageId } : {}),
      ...(options.contextId !== undefined ? { contextId: options.contextId } : {}),
      ...(options.messages !== undefined ? { messages: options.messages } : {}),
      ...(options.suppressMessageIds.length > 0 ? { suppressMessageIds: options.suppressMessageIds } : {}),
      ...(options.suppressRanges.length > 0 ? { suppressRanges: options.suppressRanges } : {}),
      marks: marks === 'none' ? 'none' : { scope: marks.scope },
    },
  };
  let result: Awaited<ReturnType<typeof createOfflineRecoveryBranch>>;
  try {
    result = await createOfflineRecoveryBranch({
      storePath: options.storePath,
      agentName: options.agentName,
      messageId: options.messageId,
      contextId: options.contextId,
      messages: options.messages,
      suppressMessageIds: options.suppressMessageIds,
      suppressRanges: options.suppressRanges,
      branchName: options.branchName,
      namespace: options.namespace,
      discordServerId: options.discordServerId,
      outboxPath: options.outboxPath,
      emoji: options.emoji,
      marks,
      dryRun: options.dryRun,
    });
  } catch (error) {
    if (!options.dryRun) recordOperatorAction(options.storePath, { ...logBase, error: errorMessage(error) });
    throw error;
  }
  if (!result.dryRun) {
    recordOperatorAction(options.storePath, {
      ...logBase,
      result: {
        sourceBranch: result.sourceBranch,
        targetBranch: result.targetBranch,
        messagesRemoved: result.messagesRemoved,
        messagesSuppressed: result.messagesSuppressed,
        discordRefs: result.discordAddressable,
        ...(result.markers ? { markers: result.markers } : {}),
      },
    });
  }

  console.log(JSON.stringify({
    ...result,
    // Keep the output useful for ops without ever exposing message content.
    refs: result.refs.map(({ serverId, channelId, messageId }) => ({ serverId, channelId, messageId })),
  }, null, 2));
}

main().catch((error) => {
  console.error(`[agent-framework-recover] ${error instanceof Error ? error.message : String(error)}`);
  process.exitCode = 1;
});
