#!/usr/bin/env node

import { JsStore } from '@animalabs/chronicle';
import { createOfflineRecoveryBranch } from './offline-branch.js';
import {
  DiscordAwarenessOutbox,
  defaultDiscordAwarenessOutboxPath,
  type DiscordAwarenessMarks,
} from './discord-awareness-outbox.js';

interface CliOptions {
  storePath?: string;
  agentName?: string;
  messageId?: string;
  contextId?: string;
  messages?: number;
  suppressMessageIds: string[];
  suppressRanges: Array<{ fromMessageId: string; toMessageId: string }>;
  branchName?: string;
  namespace?: string;
  discordServerId?: string;
  outboxPath?: string;
  emoji?: string;
  marks: 'none' | 'addressed' | 'all';
  awareness?: { verb: 'list' | 'cancel' | 'retract' | 'release'; target?: string };
  dryRun: boolean;
}

function usage(): string {
  return `Usage:
  agent-framework-recover --store <path> --agent <name> <anchor> [options]
  agent-framework-recover --store <path> --awareness <list|cancel ID|retract ID|all|release ID>
                              (cancel takes a batch id or a retract request id)

Creates and activates a Chronicle recovery branch while the normal host is
down. The recovery is local to the resident: by default no Discord reaction is
placed. --marks chooses to mark removed Discord messages with an awareness
reaction (queued here, delivered when the host and its Discord MCPL server
next connect). Message content is never compiled or written to the journal.

Options:
  --message-id <id|link>      Last Discord message the agent should still see
  --context-id <internal-id>  Exact internal context message to retain as anchor
  --messages <count>          Legacy alternative: remove N context entries
  --suppress <id|link>        Suppress one Discord message; repeat or comma-separate
  --suppress-range <a>..<b>   Suppress an inclusive context range; repeatable
  --branch <name>             Recovery branch name (generated by default)
  --namespace <namespace>     Context namespace (default: agents/<agent>)
  --discord-server <id>       Override/inject the Discord MCPL server id
  --marks <none|addressed|all>
                              Awareness marks on removed Discord messages
                              (default none; addressed = mentions, replies to
                              the bot and DMs; all = every addressable message)
  --outbox <path>             A pre-journal awareness ledger to import
                              (default: <store>/recovery/discord-awareness-outbox.json)
  --emoji <emoji>             Marker reaction (default: 💤)
  --dry-run                   Inspect counts/addresses without writing
  --help                      Show this help

Awareness journal (host stopped):
  --awareness list            Each batch: scope, counts by status, holds
  --awareness cancel <ID>     Stop further sends of a batch's marks, or of a
                              retract's removals (never undoes anything)
  --awareness retract <ID|all>
                              Queue removal of this bot's marks (through each
                              ref's configured MCPL route) on a batch's refs,
                              or on every ref an add was ever sent for
  --awareness release <ID>    Queue a held batch's recorded operations

Queued work is delivered when the host next connects to the Discord server.
The agent host must be stopped before running this command.`;
}

function parseArgs(args: string[]): CliOptions {
  const options: CliOptions = { dryRun: false, suppressMessageIds: [], suppressRanges: [], marks: 'none' };
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    const value = () => {
      const next = args[++i];
      if (!next) throw new Error(`${arg} requires a value`);
      return next;
    };
    switch (arg) {
      case '--store': options.storePath = value(); break;
      case '--agent': options.agentName = value(); break;
      case '--message-id':
      case '--message': options.messageId = value(); break;
      case '--context-id': options.contextId = value(); break;
      case '--messages': options.messages = Number(value()); break;
      case '--suppress':
      case '--suppress-message':
        options.suppressMessageIds.push(...value().split(',').map((item) => item.trim()).filter(Boolean));
        break;
      case '--suppress-range': {
        const raw = value();
        const separator = raw.indexOf('..');
        if (separator <= 0 || separator >= raw.length - 2) {
          throw new Error('--suppress-range must be formatted as <first>..<last>');
        }
        options.suppressRanges.push({
          fromMessageId: raw.slice(0, separator),
          toMessageId: raw.slice(separator + 2),
        });
        break;
      }
      case '--branch': options.branchName = value(); break;
      case '--namespace': options.namespace = value(); break;
      case '--discord-server': options.discordServerId = value(); break;
      case '--outbox': options.outboxPath = value(); break;
      case '--emoji': options.emoji = value(); break;
      case '--marks': {
        const marks = value();
        if (marks !== 'none' && marks !== 'addressed' && marks !== 'all') {
          throw new Error('--marks must be none, addressed or all');
        }
        options.marks = marks;
        break;
      }
      case '--awareness': {
        const verb = value();
        if (verb === 'list') {
          options.awareness = { verb };
        } else if (verb === 'cancel' || verb === 'retract' || verb === 'release') {
          options.awareness = { verb, target: value() };
        } else {
          throw new Error('--awareness must be list, cancel <ID>, retract <ID|all> or release <ID>');
        }
        break;
      }
      case '--dry-run': options.dryRun = true; break;
      case '--help':
      case '-h':
        console.log(usage());
        process.exit(0);
      default: throw new Error(`Unknown argument: ${arg}`);
    }
  }
  return options;
}

function awareness(options: CliOptions): void {
  // The journal lives in the store; with the host stopped, this process is
  // its only writer.
  const store = JsStore.openOrCreate({ path: options.storePath! });
  try {
    const outbox = new DiscordAwarenessOutbox(store, {
      legacyPath: options.outboxPath ?? defaultDiscordAwarenessOutboxPath(options.storePath!),
    });
    const { verb, target } = options.awareness!;
    const by = 'agent-framework-recover';
    let result: unknown;
    switch (verb) {
      case 'list': result = { store: options.storePath, batches: outbox.view() }; break;
      case 'cancel': result = outbox.cancel(target!, by); break;
      case 'retract': result = outbox.retract(target!, by); break;
      case 'release': result = outbox.release(target!, by); break;
    }
    console.log(JSON.stringify(result, null, 2));
  } finally {
    store.close();
  }
}

async function main(): Promise<void> {
  const options = parseArgs(process.argv.slice(2));
  if (options.awareness) {
    if (!options.storePath) {
      throw new Error(`--awareness needs --store\n\n${usage()}`);
    }
    awareness(options);
    return;
  }
  if (
    !options.storePath
    || !options.agentName
    || (!options.messageId && !options.contextId && options.messages === undefined)
  ) {
    throw new Error(`--store, --agent, and one anchor (--message-id, --context-id, or --messages) are required\n\n${usage()}`);
  }

  // A CLI choice and its application are the same moment (the host is
  // stopped), so the scope is evaluated now rather than frozen to refs.
  const marks: DiscordAwarenessMarks = options.marks === 'none' ? 'none' : { scope: options.marks };
  const result = await createOfflineRecoveryBranch({
    storePath: options.storePath,
    agentName: options.agentName,
    messageId: options.messageId,
    contextId: options.contextId,
    messages: options.messages,
    suppressMessageIds: options.suppressMessageIds,
    suppressRanges: options.suppressRanges,
    branchName: options.branchName,
    namespace: options.namespace,
    discordServerId: options.discordServerId,
    outboxPath: options.outboxPath,
    emoji: options.emoji,
    marks,
    dryRun: options.dryRun,
  });

  console.log(JSON.stringify({
    ...result,
    // Keep the output useful for ops without ever exposing message content.
    refs: result.refs.map(({ serverId, channelId, messageId }) => ({ serverId, channelId, messageId })),
  }, null, 2));
}

main().catch((error) => {
  console.error(`[agent-framework-recover] ${error instanceof Error ? error.message : String(error)}`);
  process.exitCode = 1;
});
